Settings:
  # Plugin prefix
  prefix: "&bU&eN&9Utilities &8&l>"
  # You can use %p% to use this prefix

  # Message if player don't have permission to use command
  denyMessage: 'Unkonwn command. Type "/help" for help.'

  # Message if configuration is reloaded
  reloadMessage: "%p% &aKonfigurasi berhasil dimuat ulang!"

  # Message if command cannot be executed in console
  denyConsoleMessage: "%p% &cCommand ini hanya dapat dijalankan oleh player"

Features:
  ## Anti Redstone Features
  AntiRedstone:

    # Enable Anti Redstone Features?
    # Default: true
    enabled: true

    # The message if player don't have permission to use redstone
    denyMessage: "&bUniv&eerse &cSecurity &8&l> &cKamu tidak bisa menggunakan &4Redstone &cdisini!"

    # All redstone components you want to turn on or off
    redstone: true
    repeater: true
    comparator: true
    redstone_torch:
      # Redstone torch has 2 categories, namely land and wall
      # You can disable any or all of them
      wall: true
      land: true

    observer: true
    redstone_block: false
    redstone_lamp: false

  ## Armor Stand Arms Adder Features
  ArmorStandArmsAdder:

    # Enable Armor Stand Arms Adder Features?
    # Default: true
    enabled: true

    # Enable log to console?
    # Default: true
    log: true

  ## Address Whitelister Features
  AddressWhitelister:

    # Enable Address Whitelister Features?
    # !!! -> You need BungeeCord to use this features
    # Default: false
    enabled: false

    # !!! -> IT MUST BE THE SAME AS IN THE BUNGEECORD config.yml UNDER 'host: '
    # !!! -> Please change your BungeeCord Address to your origin server address (e.g from your v- or rootserver). Example: 12.34.56.78
    # Default: 0.0.0.0
    address: 0.0.0.0
    # You can whitelist multiple bungeecord servers by splitting them with a ";"
    # Example: 33.44.55.66;1.23.45.56;5.6.77.88

    # The message if a player doesn't join over the whitelisted address
    kickMessage: '&cHarap menggunakan ip &aplay.&buniverse&enetwork&6.id &cuntuk bergabung'
    # You can use %enter% to go to a new line

  ## Anti Zero Tick Farm Features
  AntiZeroTickFarm:

    # Enable Anti Zero Tick Farm Features?
    # Default: true
    enabled: true

  ## Hat Command Features
  HatCommand:

    # Enable Hat Command Features?
    # Default: true
    enabled: true

    # Message if this feature is disabled
    disabledMessage: '&bUniv&eerse &aHat &8&l> &cFitur ini dinonaktifkan'

    # Message if the player uses the /hat command
    message: '&bUniv&eerse &aHat &8&l> &eBerhasil menggunakan item di tanganmu sebagai topi'

  ## Max Player Changer Command Features
  MaxPlayerChangerCommand:

    # Enable Max Player Changer Command Features?
    # Default: true
    enabled: true

    # If true, the server.properties (on Bukkit/Spigot) will be update and the new slots will be keep after the restart
    # Default: true
    SaveOnRestart: true

    # Message if this feature is disabled
    disabledMessage: '%p% &cFitur ini dinonaktifkan'

    # Message if the command successfully run without error
    # %n% = Number of max player you want to change
    successMessage: '%p% &aBerhasil mengubah jumlah maksimal player ke %n%'

    # Message if no number is given
    noArgumentMessage: '%p% &cHarap cantumkan nomor yang valid'

    # Message if argument is not a number
    invalidNumberMessage: '%p% &cHarap cantumkan nomor yang valid'

    # Message if an error has occurred
    errorMessage: '%p% &cTerjadi kesalahan, silakan periksa console!'

  ## AsyncWorldEdit BossBar Display Features
  AsyncWorldEditBossBarDisplay:

    # Enable AsyncWorldEdit BossBar Display?
    # !!! -> You need AsyncWorldEdit to use this features
    # Default: false
    enabled: false

    # Available variables are $jobsCount, $queuedBlocks, $maxQueuedBlocks, $timeLeft, $placingSpeed, $percentage
    titleFormat: "ETA: $timeLeft seconds, Speed: $placingSpeed block/sec, $percentage %"

    # Color that the progress bar should be
    # Color options are PINK,BLUE,RED,GREEN,YELLOW,PURPLE,WHITE
    barColor: "BLUE"