name: UNUtilities
version: ${project.version}
main: id.universenetwork.utilities.Bukkit.UNUtilities
api-version: 1.16
author: ARVIN3108 ID
description: Utilities Features for UniverseNetwork
website: https://universenetwork.id
provides:
  - PreventPortBypass
  - ZeroTickFarmBlocker
commands:
  universeutilities:
    description: Main command for UNUtilities
    aliases:
      - unu
      - uu
permissions:
  unutilities.*:
    default: op
    description: Grant all permissions of this plugin
    children:
      - unutilities.redstone
      - unutilities.command

  unutilities.redstone:
    default: op
    description: Permission to bypass Anti Redstone Features

  unutilities.command:
    default: op