name: ${project.name}
version: ${project.version}
main: id.universenetwork.utilities.Bukkit.UNUtilities
api-version: 1.16
author: ARVIN3108 ID
description: ${project.description}
website: ${project.url}


softdepend:
  - AsyncWorldEdit
  - ShopGUIPlus
  - SilkSpawners
  - Slimefun
  - ProtocolLib
  - Skript
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - mcMMO
  - NoCheatPlus


provides:
  - PreventPortBypass
  - ZeroTickFarmBlocker
  - Hat
  - ChangeSlots
  - AsyncWorldEditBossBar
  - ActionBarAPI
  - ShopGUIPlusSilkSpawnersBridge
  - ExtraGear
  - PrivateStorage
  - DyedBackpacks
  - SlimefunOreChunks
  - ExtraHeads
  - MobCapturer
  - ExtraTools
  - SimpleMaterialGenerators
  - PotionExpansion
  - SoulJars
  - ColoredEnderChests
  - EcoPower
  - SlimyTreeTaps
  - MoreTools
  - ChestTerminal
  - HeadLimiter
  - SoundMuffler
  - SFMobDrops
  - VillagerOptimiser
  - skript-placeholders
  - FluffyMachines
  - HotbarPets
  - ElectricSpawners
  - BookExploitFix
  - InfinityExpansion
  - ShulkerPacks
  - SkQuery


commands:
  universeutilities:
    description: Main command for UNUtilities
    aliases: [ unu, uu ]

  hat:
    description: Hat Command Features
    permission: unutilities.command.hat

  changeslots:
    description: Max Player Changer Command Features
    usage: /<command> <slots>
    aliases: [ setslots ]
    permission: unutilities.command.changeslots

  potionexpansion:
    description: PotionExpansion SlimeFun Addons Command
    aliases: [ pe ]

  mobdrops:
    description: SFMobDrops SlimeFun Addons Command
    aliases: [ sfmobdrops, mobdrop, sfmd ]

  filter:
    aliases: [ bookfilter, filterbook ]
    usage: /<command>
    description: Anti Book Exploit Command Features
    permission: unutilities.command.filter

  infinityexpansion:
    description: Do /infinityexpansion help for a list of commands
    usage: /infinityexpansion <subcommand>
    aliases: [ ie, ix, infinity ]


permissions:
  unutilities.*:
    default: op
    description: Grant all permissions of this plugin
    children:
      - unutilities.redstone
      - unutilities.command.*

  unutilities.command.*:
    default: op
    description: Grant all permissions of plugin commands
    children:
      - unutilities.command.reload
      - unutilities.command.hat
      - unutilities.command.changeslots
      - unutilities.command.filter

  unutilities.redstone:
    default: op
    description: Permission to bypass Anti Redstone Features

  unutilities.command.reload:
    default: op
    description: Permission to use reload command

  unutilities.command.hat:
    default: op
    description: Permission to use Hat Command Features

  unutilities.command.changeslots:
    default: op
    description: Permission to use Max Player Changer Command Features

  unutilities.command.filter:
    default: op
    description: Permission to use Anti Book Exploit Filter Command