name: UNUtilities
version: ${project.version}
main: id.universenetwork.utilities.Bukkit.UNUtilities
api-version: 1.16
author: ARVIN3108 ID
description: Utilities Features for UniverseNetwork
website: https://universenetwork.id
provides:
  - PreventPortBypass
  - ZeroTickFarmBlocker
  - Hat
commands:
  universeutilities:
    description: Main command for UNUtilities
    aliases:
      - unu
      - uu

  hat:
    description: Hat Command Features
permissions:
  unutilities.*:
    default: op
    description: Grant all permissions of this plugin
    children:
      - unutilities.redstone
      - unutilities.command.*

  unutilities.command.*:
    default: op
    description: Grant all permissions of plugin commands
    children:
      - unutilities.command.reload
      - unutilities.command.hat

  unutilities.redstone:
    default: op
    description: Permission to bypass Anti Redstone Features

  unutilities.command.reload:
    default: op
    description: Permission to use reload command

  unutilities.command.hat:
    default: op
    description: Permission to use Hat Command Features