Settings:
  # Plugin prefix
  # You can use %p% to use this prefix
  prefix: '&bU&eN&9Utilities &8&l>'

  # Message if player don't have permission to use command
  denyMessage: 'Unknown command. Type "/help" for help.'

  # Message if configuration is reloaded
  reloadMessage: '%p% &aKonfigurasi berhasil dimuat ulang!'

  # Message if command cannot be executed in console
  denyConsoleMessage: '%p% &cCommand ini hanya dapat dijalankan oleh player'

Features:

  ## Max Player Changer Command Features
  MaxPlayerChangerCommand:

    # Enable Max Player Changer Command Features?
    # Default: true
    enabled: true

    # If true, the server.properties (on Bukkit/Spigot) will be update and the new slots will be keep after the restart
    # Default: true
    SaveOnRestart: true

    # Does the plugin display real max players when you ping the server on server list?
    # Default: true
    UpdateServerPing: true

    # Message if this feature is disabled
    disabledMessage: '%p% &cFitur ini dinonaktifkan'

    # Message if the command successfully run without error
    # %n% = Number of max player you want to change
    successMessage: '%p% &aBerhasil mengubah jumlah maksimal player ke %n%'

    # Message if no number is given
    noArgumentMessage: '%p% &cHarap cantumkan nomor yang valid'

    # Message if argument is not a number
    invalidNumberMessage: '%p% &cHarap cantumkan nomor yang valid'

    # Message if an error has occurred
    errorMessage: '%p% &cTerjadi kesalahan, silakan periksa console!'

  ## Staff List Features
  StaffList:

    # Enable Staff List Features?
    # Default: true
    enabled: true

    # Message if player with permission "unutilities.command.stafflist" joined the server
    join-msg: '%p% &bStaff &6%player% &bhas &ajoined &bthe network!'

    # Message if player with permission "unutilities.command.stafflist" leave the server
    leave-msg: '%p% &bStaff &6%player% &bhas &cleave &bthe network!'

    # Message if this feature is disabled
    disabled-msg: '%p% &cFitur ini dinonaktifkan'

  ## Whitelister Features
  Whitelister:

    # Enable Whitelister Features?
    # Default: true
    enabled: true

    # Message if whitelist toggled on
    enabled-msg: '%p% &aWhitelist is now turned on'

    # Message if whitelist already enabled
    already-enabled-msg: '%p% &cWhitelist is already turned on'

    # Message if whitelist toggled off
    disabled-msg: '%p% &eWhitelist is now turned off'

    # Message if whitelist already disabled
    already-disabled-msg: '%p% &cWhitelist is already turned off'

    # Message if player is added to whitelist
    add-msg: '%p% &aAdded %player% to the whitelist'

    # Message if player is already added to whitelist
    already-add-msg: '%p% &cPlayer is already whitelisted'

    # Message if player is removed to whitelist
    remove-msg: '%p% &eRemoved %player% from the whitelist'

    # Message if player is not whitelisted
    not-whitelisted-msg: '%p% &cPlayer is not whitelisted'

    # Whitelist list command
    list-msg: '%p% &bThere are %count% whitelisted players: %player%'

    # Whitelist list command if no player is whitelisted
    list-no-whitelisted-message: '%p% &eThere are no whitelisted players'

    # Message if a player is kicked for not being whitelisted
    kick-msg: ''

    # Message if this feature is disabled
    disabled-feature-msg: '%p% &cFitur ini dinonaktifkan'